openapi: 3.1.0
info:
  version: 1.0.0
  title: <uygulamanızın adı>
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    <uygulamanızın açıklaması>
tags:
  # kullanacağınız etiketler
  - name: contacts
    description: Rehberdeki kişilerle ilgili işlemler
servers:
  - url: <http://localhost:3000>
    description: Yerel Geliştirme Sunucusu
  - url: #yayınlanmış siteye bağlantı
    description: Render Canlı Sunucusu
paths:
  # burada uç noktaların bağlantıları olacak
  /contacts:
    $ref: '../swagger/paths/contacts/index.yaml'
  /contacts/{contactId}:
    $ref: '../swagger/paths/contacts/{contactId}/index.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
